import type { HamRadioProduct } from './product-types';

export const cmcGenChokes = [
  {
    sku: "CMCG-UQRP-261",
    slug: "cmcg-uqrp-261",
    name: "CMC-GEN 1:1 Choke µQRP 261",
    productLine: "CMC-GEN",
    productType: "choke",
    series: "HF",
    radiatorVariant: null,
    powerLine: "µQRP",
    radiatorLength: null,
    loadingCoil: null,
    counterpoiseLength: null,
    ununCore: null,
    chokeCore: "2× Amidon FT-82-43",
    chokeCable: "RG-178",
    capacitor: null,
    ratedPower: "10 W DIGI / 15 W CW / 30 W SSB PEP",
    notes: null,
    availability: "contact",
  },
  {
    sku: "CMCG-QRP-261",
    slug: "cmcg-qrp-261",
    name: "CMC-GEN 1:1 Choke QRP 261",
    productLine: "CMC-GEN",
    productType: "choke",
    series: "HF",
    radiatorVariant: null,
    powerLine: "QRP",
    radiatorLength: null,
    loadingCoil: null,
    counterpoiseLength: null,
    ununCore: null,
    chokeCore: "2× Amidon FT-114-43",
    chokeCable: "RG-178 lub RG-316",
    capacitor: null,
    ratedPower: "20 W DIGI / 40 W CW / 100 W SSB PEP",
    notes: null,
    availability: "contact",
  },
  {
    sku: "CMCG-STD-261",
    slug: "cmcg-std-261",
    name: "CMC-GEN 1:1 Choke STD 261",
    productLine: "CMC-GEN",
    productType: "choke",
    series: "HF",
    radiatorVariant: null,
    powerLine: "STD",
    radiatorLength: null,
    loadingCoil: null,
    counterpoiseLength: null,
    ununCore: null,
    chokeCore: "3× Amidon FT-140-43",
    chokeCable: "RG-316",
    capacitor: null,
    ratedPower: "200 W DIGI / 400 W CW / 600 W SSB PEP",
    notes: null,
    availability: "contact",
  },
  {
    sku: "CMCG-HD-261",
    slug: "cmcg-hd-261",
    name: "CMC-GEN 1:1 Choke HD 261",
    productLine: "CMC-GEN",
    productType: "choke",
    series: "HF",
    radiatorVariant: null,
    powerLine: "HD",
    radiatorLength: null,
    loadingCoil: null,
    counterpoiseLength: null,
    ununCore: null,
    chokeCore: "3× Amidon FT-240-43",
    chokeCable: "RG-400",
    capacitor: null,
    ratedPower: "300 W DIGI / 800 W CW / 1500 W SSB PEP",
    notes: null,
    availability: "contact",
  },
] satisfies HamRadioProduct[];
