import type { HamRadioProduct } from './product-types';

export const genFedUnuns = [
  {
    sku: "GFU49-UQRP-261",
    slug: "gfu49-uqrp-261",
    name: "GEN-FED 1:49 Un-Un µQRP 261",
    productLine: "GEN-FED",
    productType: "un-un",
    series: "HF",
    radiatorVariant: null,
    powerLine: "µQRP",
    radiatorLength: null,
    loadingCoil: null,
    counterpoiseLength: null,
    ununCore: "2× Amidon FT-82-43",
    chokeCore: null,
    chokeCable: null,
    capacitor: "100 pF / 2 kV / C0G/NP0",
    ratedPower: "10 W DIGI / 15 W CW / 30 W SSB PEP",
    notes: "Un-Un bez wersji S/M",
    availability: "contact",
  },
  {
    sku: "GFU49-QRP-261",
    slug: "gfu49-qrp-261",
    name: "GEN-FED 1:49 Un-Un QRP 261",
    productLine: "GEN-FED",
    productType: "un-un",
    series: "HF",
    radiatorVariant: null,
    powerLine: "QRP",
    radiatorLength: null,
    loadingCoil: null,
    counterpoiseLength: null,
    ununCore: "2× Amidon FT-114-43",
    chokeCore: null,
    chokeCable: null,
    capacitor: "100 pF / 3 kV / C0G/NP0",
    ratedPower: "20 W DIGI / 40 W CW / 100 W SSB PEP",
    notes: "Un-Un bez wersji S/M",
    availability: "contact",
  },
  {
    sku: "GFU49-STD-261",
    slug: "gfu49-std-261",
    name: "GEN-FED 1:49 Un-Un STD 261",
    productLine: "GEN-FED",
    productType: "un-un",
    series: "HF",
    radiatorVariant: null,
    powerLine: "STD",
    radiatorLength: null,
    loadingCoil: null,
    counterpoiseLength: null,
    ununCore: "3× Amidon FT-140-43",
    chokeCore: null,
    chokeCable: null,
    capacitor: "100 pF / 5 kV / C0G/NP0 lub mikowy",
    ratedPower: "100 W DIGI / 200 W CW / 300 W SSB PEP",
    notes: "Un-Un bez wersji S/M",
    availability: "contact",
  },
  {
    sku: "GFU49-HD-261",
    slug: "gfu49-hd-261",
    name: "GEN-FED 1:49 Un-Un HD 261",
    productLine: "GEN-FED",
    productType: "un-un",
    series: "HF",
    radiatorVariant: null,
    powerLine: "HD",
    radiatorLength: null,
    loadingCoil: null,
    counterpoiseLength: null,
    ununCore: "3× Amidon FT-240-43",
    chokeCore: null,
    chokeCable: null,
    capacitor: "100 pF / 10 kV / C0G/NP0 lub mikowy",
    ratedPower: "300 W DIGI / 800 W CW / 1500 W SSB PEP",
    notes: "Un-Un bez wersji S/M",
    availability: "contact",
  },
] satisfies HamRadioProduct[];
